name: Docs

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: 2
  NODE: 16

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "${{ env.NODE }}"
          cache: npm

      - run: java -version

      - name: Install npm dependencies
        run: npm ci

      - name: Test docs
        run: npm run docs

      - name: Run accessibility tests
        run: npm run docs-accessibility

      - name: Upload accessibility results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: pa11yci-report
          path: pa11yci-report.html
          if-no-files-found: error
